# .github/workflows/main.yml

name: Scrape RAWG Similar Games

on:
  # Mantém o agendamento e o gatilho manual (opcional)
  schedule:
    - cron: '0 3 * * 1' # Ex: Roda toda segunda-feira às 3 da manhã
  workflow_dispatch:

  # ADICIONA O NOVO GATILHO EXTERNO
  repository_dispatch:
    types: [scrape-new-game] # Deve ser o mesmo 'event_type' do backend

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Ou a versão que você usa

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium # Instala o navegador para o Playwright

      - name: Run Scraper
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: 
          if [[ "${{ github.event.action }}" == "scrape-new-game" ]]; then
            echo "Rodando scraper para um jogo específico..."
            # Pega o nome do jogo do payload e passa como argumento
            python scraper.py "${{ github.event.client_payload.game }}"
          else
            echo "Rodando scraper completo (scan geral)..."
            python scraper.py
          fi